default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= ENV['VOLUN_DATABASE_USER_DEVELOPMENT'] %>
  password: <%= ENV['VOLUN_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: volun_development

test:
  <<: *default
  database: volun_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
