default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('VOLUN_DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('VOLUN_DATABASE_PORT', 5432) %>
  username: <%= ENV['VOLUN_DATABASE_USER'] %>
  password: <%= ENV['VOLUN_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: volun_development

test:
  <<: *default
  database: volun_test

production:
  primary: &primary_production
    <<: *default
    database: volun_production
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production
    database: volun_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: volun_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: volun_production_cable
    migrations_paths: db/cable_migrate
